### ISSUE TITLE
UnexpectedDataSize Error loading europe-latest

### ISSUE THREAD

**Issue by RoffelKartoffel** [boxdot/osmflat-rs#61]
I have compiled `europe-latest.osm.pbf` as follows `osmflatc europe-latest.osm.pbf europe-latest.osm.flatdata`.

When loading `europe-latest.osm.flatdata` I get the following error: ` Err value: UnexpectedDataSize`

Smaller data sets, e.g. bremen-latest, work fine for me.

**Comment by VeaaC** [comment]
Are you maybe compiling the application in 32 bit mode? libosmflat is using memory mapped files for reading the data, and that means it has to map the whole file into memory. 32 bit mode only supports up to 2GB (sometimes 3GB) large files.

**Comment by RoffelKartoffel** [comment]
`osmflatc` as well as my executable are 64 bit. `file` says `ELF 64-bit LSB pie executable, x86-64`.

**Comment by RoffelKartoffel** [comment]
The input `europe-latest.osm.pbf` is around 30GB large. Did you ever test with files of that size? I could imagine, that I hit some kind of format limitation there. I obtained the file from here: https://download.openstreetmap.fr/extracts/europe-latest.osm.pbf

**Comment by boxdot** [comment]
I compiled the Europe pbf on my Fedora machine (AMD Ryzen 9 5900X, 32G RAM). I get a 87G uncompressed flatdata archive. The `road-length` example works fine with it. (After switching to a parallel iterator inside to increase the IO throughput, otherwise it is quite slow.) My result is `Length: 20834518 km`

@RoffelKartoffel Maybe you could provide us more information about your system and hardware?

**Comment by RoffelKartoffel** [comment]
I could not reproduce the exact error today, but I noticed, that `osmflatc` dies on me for the `europe-latest.osm.pbf` . It eats up the available 32GB RAM and dies. The terminal logs a simplistic german `Getötet`. I guess, I overlook the message before... my bad.

So today I added a swap file of 32GB too, and the generated `flatdata` works fine :)

Maybe some flag written at the verry end of the generation process would be helpfull. So that loading incomplete `flatdata` fails with a more helpfull message.

For documentation: CPU is a `Intel(R) Core(TM) i7-11800H`. The system has 32GB RAM. I am running `Arch Linux`, kernel version is `5.17.9-arch1-1` .

Thank you for your patience! Please close this bug, if you consider it done / do not like my proposal.

**Comment by VeaaC** [comment]
osmflat compilation itself uses quite some memory (mostly to resolve millions of OSM identifiers, something that you do not have to do anymore if you work with osmflat directly instead of PBF files). I totally agree with you that the error message is not too useful (it is the result of an internal flatdata check: It compares the size the file should have in its meta-data with the one it actually has... and isnce osmflatc died before finishing writing the file these disagree).

I will keep this bug around for a few more days and try to add more useful error output (either in osmflat, or directly upstream in flatdata).

**Comment by VeaaC** [comment]
Closing, as it was an out-of-memory problem, and we could not come up with better diagnostics
